version: '3'

services:
  dockerdb:
    image: postgres:alpine
    container_name: dockerdb
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dockerdb
    ports:
      - '5432:5432'
    volumes:
      # copy the sql script to create tables
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "create_topic:1:1,update_topic:1:1,delete_topic:1:1,employee_events:1:1"
