create table if not exists public.employee
(
    id        bigint generated always as identity
    constraint employee_pk
    primary key,
    email     varchar not null
    unique,
    full_name varchar not null,
    birthday  date    not null
);

comment on column public.employee.id is 'primary key';

alter table public.employee
    owner to postgres;

create table if not exists public.hobby
(
    id   bigint generated by default as identity
    constraint hobby_pk
    primary key,
    name varchar not null
    unique
);

alter table public.hobby
    owner to postgres;

create table if not exists public.employee_hobby
(
    employee_id bigint not null
    constraint employee__fk
    references public.employee,
    hobby_id    bigint not null
    constraint hobby__fk
    references public.hobby,
    constraint employee_hobby_pk
    primary key (employee_id, hobby_id)
    );

alter table public.employee_hobby
    owner to postgres;

